### PR TITLE
Update to version 0.5.0

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
@ocefpaf this is rebased against master (#21 was just merged). But Python3.7 on travis fails (2.7 has an issue, that is known, ignore that). Did you see this error before?

**Comment by ocefpaf** [comment]
Let's go with the standard re-rendering until I fix the 3.7 stack.


@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> I tried to re-render for you, but it looks like there was nothing to do.

The bot is not OK :-/

I'll do that manually in a sec, hold on...

**Comment by maartenbreddels** [comment]
No, should be fine, #21 was a rerender, and I rebased this.

**Comment by ocefpaf** [comment]
> No, should be fine, #21 was a rerender, and I rebased this.

Not really b/c the standard re-render should delete my "hacked" Python 3.7.

**Comment by maartenbreddels** [comment]
Do you mind if I merge this when ready, and we rerender later? I'd like to release this asap :)

**Comment by maartenbreddels** [comment]
Btw, AppVeyor seems to take a long time, if I merge this now, will the windows version eventually land on the conda-forge channel?

**Comment by ocefpaf** [comment]
> Btw, AppVeyor seems to take a long time, if I merge this now, will the windows version eventually land on the conda-forge channel?

The queue is huge at the moment. Feel free to merge it and I'll monitor the build sin case we need to fix anything later.

**Pull request merged**
