### PR TITLE
Ipyvolume 0.6.0a8, add maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Congrats on 0.6.0a8!

Just did some spring cleaning on the recipe. I've not put myself down as a maintainer, but happy to do so if you need more hands!

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/ipyvolume ready for review!

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/ipyvolume added myself, back to ready for review!

**Comment by maartenbreddels** [comment]
Awesome Nick! Thanks.

**Comment by bollwyvl** [comment]
Hooray!

**Pull request merged**
