### PR TITLE
Fix linking Jupyter extension on Windows. Fix #208

### PR DESCRIPTION
**Pull request by hadim**
I don't really understand why `PREFIX` does not work but at least now it works for me locally on Windows 10. Let's see what happen on Appveyor.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Probably because jupyter is installed in %LIBRARY_PREFIX%, not %PREFIX%.

**Comment by SylvainCorlay** [comment]
Sorry I was mistaken.

**Comment by SylvainCorlay** [comment]
A postlink script that works on bqplot is

https://github.com/conda-forge/bqplot-feedstock/blob/master/recipe/post-link.bat

**Comment by hadim** [comment]
The original script is the same as the bqplot's one. Have you been able to reproduce the issue no your computer locally?

**Comment by SylvainCorlay** [comment]
I am afk. Do you have the detail of the error?

**Comment by hadim** [comment]
https://github.com/maartenbreddels/ipyvolume/issues/208

**Comment by SylvainCorlay** [comment]
So this is not showing a lot but post link scripts are executedbin empty environment (besides jupyter core which is hard coded by conda). So if the __init__.py of ipyvolume imports anything that is not there, the post link script will fail.

**Comment by hadim** [comment]
Sorry, I don't understand what you mean. For me locally using `"%PREFIX%\Scripts\jupyter-nbextension.exe" enable ipyvolume` fails while using `"jupyter-nbextension.exe" enable ipyvolume` it works.

What is the relationship with `ipyvolume` import?

**Comment by SylvainCorlay** [comment]
Did you define PREFIX locally? If you set the PREFIX environment variable to the root of your anaconda installation, both will work.

**Comment by hadim** [comment]
I first modify the post link script, then build the recipe `conda build recipe` and then try to install the package. This is where I see the error. So I assume PREFIX is defined since it's running inside Conda.

**Comment by hadim** [comment]
Thank you. I didn't try with `bqplot` (AFK from a Windows machine at the moment).

**Comment by hadim** [comment]
`bqplot` installation works on Windows for me.

**Comment by hadim** [comment]
@SylvainCorlay did you have time to have a look?

**Comment by maartenbreddels** [comment]
Given that bqplot does have the same script, I guess it is not that. Could you try updating ipywidget to 7.4 before installing?

**Comment by hadim** [comment]
If you look at the logs I have posted at https://github.com/maartenbreddels/ipyvolume/issues/208#issue-383365388, you can see that install fails from a clean env and also a clean Conda installation.

```
python:                 7.1.1-py37h39e3cac_1000   conda-forge
    ipython_genutils:        0.2.0-py_1                conda-forge
    ipyvolume:               0.5.1-py37_1000           conda-forge
    ipywebrtc:               0.4.2-py37_1000           conda-forge
    ipywidgets:              7.4.2-py_0                conda-forge
    jedi:                    0.13.1-py37_1000          conda-forge
    jinja2:                  2.10-py_1                 conda-forge
    jpeg:                    9b-vc14_2                 conda-forge [vc14]
    jsonschema:              3.0.0a3-py37_1000         conda-forge
```

**Comment by hadim** [comment]
@maartenbreddels the last commit forces `pillow >5.2`. I think it will fix deps issue on Windows but I would understand if you want to support lower Pillow version and I'll remove it.

**Comment by maartenbreddels** [comment]
Could you do a conditional version requirements? I guess conda supports that right?

**Comment by glyg** [comment]
```
host:
  - numpy 1.9.3              # [unix]
  - numpy 1.11.3             # [win]
```
per conda-forge [docs](https://conda-forge.org/docs/meta.html#building-against-numpy)

**Comment by maartenbreddels** [comment]
Could you add a comment in the recipe with a link to this thread so we have a reference back to the explanation?
Many thanks! (hope it builds)

**Comment by maartenbreddels** [comment]
Awesome work, thanks a lot!

**Pull request merged**
